beta: 0.5
bf16: true
dataset_mixer:
  /data/user_data/wentaos/Optima/temp_datasets/mwh_qa_dpo_mixHILQ_warmup_8000_100/iteration_0: 1.0
dataset_splits:
- train
- test
do_eval: true
eval_steps: 100
evaluation_strategy: steps
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-07
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 4096
max_prompt_length: 1024
model_name_or_path: /data/group_data/cx_group/MCTS-agent/checkpoints/mwh_qa_sft_dpo_DI/DITS_mwh_qa_sft_iteration_0
model_revision: main
num_train_epochs: 1
optim: adamw_torch
output_dir: /data/group_data/cx_group/MCTS-agent/checkpoints/mwh_qa_dpo_mixHILQ_warmup_8000_100/dpo_iteration_0
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
preprocessing_num_workers: 8
save_strategy: 'steps'
save_steps: 20
save_total_limit: 1
seed: 42
tokenizer_name_or_path: /data/user_data/wentaos/Huggingface_models/Llama-3-8B-Instruct
torch_dtype: bfloat16
use_flash_attention_2: true
warmup_ratio: 0.1
